networks:
  # connects airflow -> minio
  my_bridge:
    driver: bridge

# debian
services:
  airflow:
    build: .
    container_name: airflow_dev
    restart: always
    #tty: true # keep container running
    #stdin_open: true # enable interactive shell 
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////home/airflow/airflow.db
      - AIRFLOW__SMTP__SMTP_HOST=host.docker.internal
      - AIRFLOW__SMTP__SMTP_SSL=False
      - AIRFLOW__SMTP__SMTP_STARTTLS=False
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=no-reply@example.com
      - AIRFLOW__SMTP__SMTP_PORT=1025
    volumes:
      - ./airflow-dags:/home/airflow/dags
      - ./airflow-tmp:/home/airflow/tmp
    ports:
      - "8080:8080"
    networks:
        - my_bridge
        
  # minio : an aws s3 dropin replacement for on prem s3 like bucket
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - ./minio_data:/data
    networks:
        - my_bridge

  minio-client:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
    volumes:
      - ./minio-client:/data
    entrypoint: >
      /bin/sh -c "
      echo 'minio-client : setup';
      ls -al /data;
      sleep 15;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb local/airflow-dev;
      mc policy set public local/airflow-dev;
      mc cp /data/data.csv local/airflow-dev;
      mc ls local/airflow-dev;
      while true; do sleep 3600; done;
      "
    networks:
        - my_bridge 

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-src:/src
    # entrypoint: >
    #   /bin/sh -c "
    #   alias ll='ls -al';
    #   "
