# debian
services:
  airflow:
    build: .
    container_name: airflow_dev
    restart: always
    #tty: true # keep container running
    #stdin_open: true # enable interactive shell 
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////home/airflow/airflow.db
    volumes:
      - ./dags:/home/airflow/dags
      - ./src:/home/airflow/src
    ports:
      - "8080:8080"
        
  # minio : an aws s3 dropin replacement for on prem s3 like bucket
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - ./minio_data:/data

  minio-client:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
    volumes:
      - ./minio-client:/data
    entrypoint: >
      /bin/sh -c "
      echo 'minio-client : setup';
      ls -al /data;
      sleep 15;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb local/airflow-dev;
      mc policy set public local/airflow-dev;
      mc cp /data/data.csv local/airflow-dev;
      mc ls local/airflow-dev;
      while true; do sleep 3600; done;
      "
